### ISSUE TITLE
add ctl schema command

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/form-api#161]
`form-api ctl schema --for=create|get|update|delete`

```yaml
kind: Schema|Template|...
payload:
  ID%TYPE: string
  Some%TYPE: other
```
